#spring.application.name=book_service
#server.port=8080
#
#feign.client.config.author-service.connectTimeout=5000
#feign.client.config.author-service.readTimeout=5000
#feign.client.config.default.loggerLevel = full
#
#eureka.client.serviceUrl.defaultZone= ${EUREKA_URI:http://localhost:8761/eureka}
#eureka.client.instance.preferIpAddress= true


server:
  port: 8080
spring:
  application:
    name: book_service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
logging:
  pattern:
    console: "%msg%n"
