#spring.application.name=service_registry
#server.port=8761
#eureka.client.registerWithEureka=false
#eureka.client.fetchRegistry=false

spring:
  application:
    name: service_registry

server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

#logging:
#  pattern:
#    console: "%msg%n"
#  instance:
#    prefer-ip-address: true # This is important for the Docker container to work
